apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1
  version: "1.29"

autoModeConfig:
  enabled: false

vpc:
  nat:
    gateway: Single

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    amiFamily: AmazonLinux2
    privateNetworking: false
